name:                 hello-world
version:              1.1.0.5
visibility:           public
id:                   hello-world-1.1.0.5-HKN6tIILnZaLtklbSc44Iz
key:                  hello-world-1.1.0.5-HKN6tIILnZaLtklbSc44Iz
abi:                  e56e31df8e08cc819c59cccf52c2724d
exposed:              True
exposed-modules:      HelloWorld
hidden-modules:       Paths_hello_world
import-dirs:
    T:\Repositories\MyExercism\haskell\hello-world\.stack-work\install\cfd3d043\lib\x86_64-windows-ghc-9.2.7\hello-world-1.1.0.5-HKN6tIILnZaLtklbSc44Iz

library-dirs:
    T:\Repositories\MyExercism\haskell\hello-world\.stack-work\install\cfd3d043\lib\x86_64-windows-ghc-9.2.7\hello-world-1.1.0.5-HKN6tIILnZaLtklbSc44Iz
    C:\Users\karcagtamas\AppData\Local\Programs\stack\x86_64-windows\msys2-20230526\mingw64\lib
    C:\Users\karcagtamas\AppData\Local\Programs\stack\x86_64-windows\msys2-20230526\mingw64\bin

dynamic-library-dirs:
    T:\Repositories\MyExercism\haskell\hello-world\.stack-work\install\cfd3d043\lib\x86_64-windows-ghc-9.2.7
    C:\Users\karcagtamas\AppData\Local\Programs\stack\x86_64-windows\msys2-20230526\mingw64\lib
    C:\Users\karcagtamas\AppData\Local\Programs\stack\x86_64-windows\msys2-20230526\mingw64\bin

data-dir:
    T:\Repositories\MyExercism\haskell\hello-world\.stack-work\install\cfd3d043\share\x86_64-windows-ghc-9.2.7\hello-world-1.1.0.5

hs-libraries:         HShello-world-1.1.0.5-HKN6tIILnZaLtklbSc44Iz
include-dirs:
    C:\Users\karcagtamas\AppData\Local\Programs\stack\x86_64-windows\msys2-20230526\mingw64\include

depends:              base-4.16.4.0
haddock-interfaces:
    T:\Repositories\MyExercism\haskell\hello-world\.stack-work\install\cfd3d043\doc\hello-world-1.1.0.5\hello-world.haddock

haddock-html:
    T:\Repositories\MyExercism\haskell\hello-world\.stack-work\install\cfd3d043\doc\hello-world-1.1.0.5
